spring: #띄어쓰기 없음
  # MySQL
  datasource: #띄어쓰기 2칸
    url: jdbc:mysql://${PUBLIC_IP}:3500/mate #4칸
    username: ${DB_USER_NAME}
    password: ${DB_USER_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa: #띄어쓰기 2칸
    hibernate: #띄어쓰기 4칸
      ddl-auto: update #띄어쓰기 6칸
    properties: #띄어쓰기 4칸
      hibernate: #띄어쓰기 6칸
        #        show_sql: true   #띄어쓰기 8칸
        format_sql: true  #띄어쓰기 8칸
        default_batch_fetch_size: 1000 #최적화 옵션
logging.level: #띄어쓰기 없음
  org.hibernate.SQL: debug #띄어쓰기 2칸
#  org.hibernate.type: trace #띄어쓰기 2칸

# SSL
server:
  port: 443
  ssl:
    key-store: ${SSL_KEY}
    key-store-type: PKCS12
    key-store-password: ${SSL_PASSWORD}
