# MySQL
spring:
  datasource:
    url: jdbc:mysql://${PUBLIC_IP}:3500/mate
    username: ${DB_USER_NAME}
    password: ${DB_USER_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

# Hibernate
jpa:
  database-platform: org.hibernate.dialect.MySQLDialect
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
    #        show_sql: true
    format_sql: true
    default_batch_fetch_size: 1000 #최적화 옵션

# SSL
server:
  port: 443
  ssl:
    key-store: classpath:${SSL_KEY_PATH}
    key-store-type: PKCS12
    key-store-password: ${SSL_PASSWORD}

# JPA 쿼리 로깅 활성화
logging:
  level:
    org:
      hibernate:
        SQL: debug
      hibernate.type.descriptor.sql.BasicBinder: trace